Tie CSRF token to session Id
peeringdb/peeringdb pull request #1183
Opened 2022-06-07 17:08 UTC by prithvimanikonda

The CSRF tokens are currently not tied to a session that opens the door for the old tokens created to be used as they are still dangling around when the session is closed. Also, it exposes the risk of cross account usability of CSRF token. 

Here are more details about that flags in Django:

https://docs.djangoproject.com/en/4.0/ref/settings/#std-setting-CSRF_USE_SESSIONS

2022-06-07 18:11 UTC, grizz commented
Will need to test with deploy and ensure correct ordering:

> [SessionMiddleware](https://docs.djangoproject.com/en/4.0/ref/middleware/#django.contrib.sessions.middleware.SessionMiddleware) must appear in [MIDDLEWARE](https://docs.djangoproject.com/en/4.0/ref/settings/#std-setting-MIDDLEWARE) before any middleware that may raise an exception to trigger an error view (such as [PermissionDenied](https://docs.djangoproject.com/en/4.0/ref/exceptions/#django.core.exceptions.PermissionDenied)) if you’re using CSRF_USE_SESSIONS. See [Middleware ordering](https://docs.djangoproject.com/en/4.0/ref/middleware/#middleware-ordering).

From https://docs.djangoproject.com/en/4.0/ref/settings/#std-setting-CSRF_USE_SESSIONS

2022-06-07 18:12 UTC, grizz approved these changes

2022-06-08 16:35 UTC, prithvimanikonda commented
> Will need to test with deploy and ensure correct ordering:
> 
> > [SessionMiddleware](https://docs.djangoproject.com/en/4.0/ref/middleware/#django.contrib.sessions.middleware.SessionMiddleware) must appear in [MIDDLEWARE](https://docs.djangoproject.com/en/4.0/ref/settings/#std-setting-MIDDLEWARE) before any middleware that may raise an exception to trigger an error view (such as [PermissionDenied](https://docs.djangoproject.com/en/4.0/ref/exceptions/#django.core.exceptions.PermissionDenied)) if you’re using CSRF_USE_SESSIONS. See [Middleware ordering](https://docs.djangoproject.com/en/4.0/ref/middleware/#middleware-ordering).
> 
> From https://docs.djangoproject.com/en/4.0/ref/settings/#std-setting-CSRF_USE_SESSIONS

I have tested this out on my local container and i works fine. The ordering is as expected from what I can tell. Is there any other better way that you suggest for testing?

2022-06-09 08:23 UTC, vegu commented
Change causes AJAX `POST`,  `PUT` and `DELETE` requests to fail with `CSRF Failed: CSRF token missing or incorrect.`

From the django documentation it looks like we may need to alter how the CSRF token is acquired on the javascript end.

https://docs.djangoproject.com/en/4.0/ref/csrf/#acquiring-the-token-if-csrf-use-sessions-or-csrf-cookie-httponly-is-true

**To reproduce**

- go to `/fac/1`
- click edit
- add some changes to any of the fields (notes field for example)
- click save

2022-06-09 08:26 UTC, vegu requested changes
Need some changes on the token acquisition for AJAX requests, see details at https://github.com/peeringdb/peeringdb/pull/1183#issuecomment-1150823490

2022-06-09 20:42 UTC, prithvimanikonda commented
> Change causes AJAX `POST`, `PUT` and `DELETE` requests to fail with `CSRF Failed: CSRF token missing or incorrect.`
> 
> From the django documentation it looks like we may need to alter how the CSRF token is acquired on the javascript end.
> 
> https://docs.djangoproject.com/en/4.0/ref/csrf/#acquiring-the-token-if-csrf-use-sessions-or-csrf-cookie-httponly-is-true
> 
> **To reproduce**
> 
> * go to `/fac/1`
> * click edit
> * add some changes to any of the fields (notes field for example)
> * click save

I tested it on my local again with the steps you mentioned and I was not able to reproduce that.

Header:
```
Host: localhost:8000
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:91.0) Gecko/20100101 Firefox/91.0
Accept: application/json, text/javascript, */*; q=0.01
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Content-Type: application/json
X-CSRFToken: xiU3ZJYwlRNKMiPEAO0m8aMwSzktQY8BEz6v66CYOTnHTwowv0fF9ZMQtYMZ7K8r
X-Requested-With: XMLHttpRequest
Content-Length: 547
Origin: http://localhost:8000
Connection: keep-alive
Referer: http://localhost:8000/fac/1
Cookie: sessionid=xcgsxd8x68wg967zov39vcpmqj0f0en3; django_language=en
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
```
Payload:
```
{"_valid":true,"name":"Equinix DC1-DC15, DC21 - Ashburn","_changed":1,"aka":"","name_long":"","website":"http://www.equinix.com/","address1":"21715 Filigree Ct","address2":"Building F","floor":"","suite":"","city":"Ashburn","state":"VA","zipcode":"20147-6205","country":"US","clli":"ASBNVA","npanxx":"703-723","notes":"testing again","tech_email":"","tech_phone":"","sales_email":"","sales_phone":"","property":"","diverse_serving_substations":"","available_voltage_services":null,"status_dashboard":"","_validationErrors":{},"_id":1,"org_id":"2"}
```

When I tested this, I got the expected response:
```
{"data": [{"id": 1, "org_id": 2, "org_name": "Equinix, Inc.", "org": {"id": 2, "name": "Equinix, Inc.", "aka": "", "name_long": "", "website": "http://www.equinix.com", "notes": "", "address1": "1 Lagoon Dr", "address2": "", "city": "Redwood City", "country": "US", "state": "CA", "zipcode": "94065-1562", "floor": "", "suite": "", "latitude": 37.527344, "longitude": -122.261179, "created": "2022-05-31T20:51:14.101543Z", "updated": "2022-05-31T20:51:14.101569Z", "status": "ok", "_grainy": "peeringdb.organization.2"}, "name": "Equinix DC1-DC15, DC21 - Ashburn", "aka": "", "name_long": "", "website": "http://www.equinix.com/", "clli": "ASBNVA", "rencode": "", "npanxx": "703-723", "notes": "testing again", "net_count": 415, "ix_count": 4, "sales_email": "", "sales_phone": "", "tech_email": "", "tech_phone": "", "available_voltage_services": null, "diverse_serving_substations": null, "property": "", "region_continent": "North America", "status_dashboard": "", "created": "2022-05-31T20:54:53.119451Z", "updated": "2022-06-09T20:37:46.333522Z", "status": "ok", "address1": "21715 Filigree Ct", "address2": "Building F", "city": "Ashburn", "country": "US", "state": "VA", "zipcode": "20147-6205", "floor": "", "suite": "", "latitude": 39.016363, "longitude": -77.459023}], "meta": {}}
```

2022-06-10 08:46 UTC, vegu commented
@prithvimanikonda i think this may be an issue when there is already a csrf cookie established from before, which was the case for me.

To start with, testing in incognito mode i cannot reproduce the issue.

Then i tried simply logging out and re-authenticating on my normal chrome session, which did not fix the problem.

Finally, after manually removing all the cookies everything works correctly again. However i suspect simply removing the csrf cookie would have been sufficient.

This seems like this is something that will affect anyone who had a cookies established before we roll this change.

2022-06-10 17:00 UTC, prithvimanikonda commented
> @prithvimanikonda i think this may be an issue when there is already a csrf cookie established from before, which was the case for me.
> 
> To start with, testing in incognito mode i cannot reproduce the issue.
> 
> Then i tried simply logging out and re-authenticating on my normal chrome session, which did not fix the problem.
> 
> Finally, after manually removing all the cookies everything works correctly again. However i suspect simply removing the csrf cookie would have been sufficient.
> 
> Im concerned that this may be something that will affect anyone who had a cookies established before we roll out this change.

Yup, if we have a cookie already then I am able to reproduce this. The fix you suggested should fix that as that would change the retrieval mechanism for the cookie. I will give that a shot

2022-06-10 17:09 UTC, prithvimanikonda commented
@vegu A published a new revision on this pull request. I tried reproducing this with the cookie being present and it worked like charm this time.

2022-06-13 08:52 UTC, vegu commented
> @vegu A published a new revision on this pull request. I tried reproducing this with the cookie being present and it worked like charm this time.

Can confirm that this is now fixed, and ready to be merged. Thanks!

2022-06-13 08:52 UTC, vegu approved these changes

2022-06-15 12:23 UTC, merged